### ISSUE TITLE
Please drop the copyright for this software...thanks in advance :-)

### ISSUE THREAD

**Issue by OnePressTech** [bluehost/wp-tools#3]
It is fantastic that you have open sourced this software to the community under GPL but you have withdrawn that value by copyrighting the software. Under general copyright law people cannot make a copy, make modifications. or make distributions without your express written permission.

Thanks in advance :-)

**Comment by brianlayman** [comment]
That's not the way copyright interacts with GPL.  Read this article for more information.
http://twiki.org/cgi-bin/view/Blog/BlogEntry201207x1

For a new piece of GPL software, if a person puts a copyright notice in it, the person who creates a new version of it cannot change the license.  However, the original copyright person CAN release the software under a different license.  If there was not a copyright notice and just the license, the original author would have to contact every contributor asking for permission to release under a new license as each would natively own the code they contributed.

Now if we were not talking new code, but instead a derived code, the copyright/ownership of the whole product still falls into either of the categories mentioned above, but it is my understanding that you can copyright just the code you changed and consider it its own entity/IP as far as the above paragraphs.  Note that every WordPress plugin is considered derived from the WordPress core because it is non-functional without the core WordPress GPL code. And that's where things get tricky because you can't release the plugin as a whole under any non GPL compatible license, but you still own that IP.  And that just gets messy.   But what they've done here with it being copyrighted and GPLed is great, it just means you can't sell this code under any other (non-compatible) license. But you can contribute to it, branch it and change it to meet your needs.

**Comment by jaredsmith** [comment]
I think you're misunderstanding how open source software, and in particular software licensed under the GPL license, works with copyright law.

Open source software (including GPL software) is copyrighted by the author or authors of the software.  That alone would make it generally illegal to copy, etc. without permissions.  But by also stating (typically right next to the copyright statement) that the software is licensed under the GPL, it's in essence saying "If you follow the terms of the GPL, you can use, copy, make modifications, and distribute your modifications.  If you don't follow the terms of the GPL, standard copright law applies."

If you look at other popular open source software (such as WordPress itself, or Apache), you'll see that it's copyrighted and then licensed under a free software license.  Even the Free Software Foundation's webpage on on to use the GPL license for your own software specifically states in no uncertain terms that your software should have a copyright statement.  See http://www.gnu.org/licenses/gpl-howto.en.html for more details.  This article from the Software Freedom Law Center may also give you some further insight: http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

**Comment by OnePressTech** [comment]
Sorry guys but copyright law and licensing (contract law) are two different areas of law. One may supercede the other. The references you provided as the basis for your using copyright are not from lawyers. Please see the following article: https://www.law.washington.edu/lta/swp/law/contractvlicense.html . The last line is consistent with other advice I have received from lawyers in the past...
 " It remains to be seen whether a court would declare the license [sic GPL] as a whole unenforceable under contract law, but uphold the purely copyright law-based licenses and provisions. "

It is your software and you can choose to release it as you see fit but you do not need to include a copyright statement. By definition copyright is a statement of rights constraint. Used in conjunction with a GPL license this simply created conflicting legal constraints.

 It you would like attribution you can choose to release with a Creative Commons license with attribution rather than Copyright. If you want the copyleft protection you can release in conjunction with GPL. Although this combination would also create a constraint conflict the worst case interpretation is that the user has full rights without attribution.

Up to you guys...it's your software.

**Comment by jaredsmith** [comment]
Again, I'm not a lawyer (and don't play one on the internet), but this isn't my first foray into software licensing.  And yes, I understand that copyright law and contract law are traditionally very different aspects of the law.  However, I personally don't believe the GPL is a "contract" in the traditional sense, because it doesn't need to be signed and witnessed by the parties to be relied upon.  It's a grant of permission (or license) to use the software under the provided terms.

Let me make another analogy, if I may, that might help you understand where I"m coming from.

Let's say for sake of argument that I'm a musician, and write a new song.  If wouldn't be unreasonable for me to include a copyright statement that said something like "(C) Copyright 2016 Jared Smith.  May be used for personal/non-commercial use."  In that case, I'm declaring that I own the copyright, but that I'm willing to relax the normal rules of copyright for personal or non-commercial use.

The spirit of the GPL is very much along those same lines.  It's saying "I am the copyright holder.  I created the work, and I'm the one who gets to choose how it gets used.  That being said, I'm willing to relax or set aside some of the normal copyright restrictions, as long as you follow these rules."  That's a big difference from saying "(C) Copyright 2016 Jared Smith. All rights reserved."

And you state that neither of the articles I linked to were written by lawyers.  The Software Freedom Law Center _is_ a group of lawyers that work to help companies understand open source law.  Also, the Free Software Foundation is the group (started by Richard Stallman) that created the GPL license in the first place, so I consider both groups to be experts on the GPL and how it applies to copyright law.

But even if you're willing to dismiss that for a moment, look at other open source software and how it's coprighted.  WordPress is copyrighted.  Apache is copyrighted.  Firefox is copyrighted.  LibreOffice is copyrighted.  The Linux kernel is copyrighted.  Simply stated, all significant open source software is copyrighted by the owner, and then those restrictions are relaxed by the term of the license.

**Comment by OnePressTech** [comment]
Thanks for your patience Jared. I am convinced :-)

My suggestion had a flaw I had not appreciated and that is copyright, unlike trademark, is enforceable whether stated or unstated as of 1988 (I am 56 so a number of conversations with corporate lawyers related to copyright were mid-80's) AND it appears that there are currently no consistent laws to waive copyright. Creative Commons licenses are an attempt to make that simpler in a "sharing / caring" internet world but they also appear to be merely another rights license.

It has always been true, though, that courts take into consideration explicit statements of intent in resolving conflicting or overlapping legal documents. With that in mind one could argue that a Creative Commons license in conjunction with a GPL license is a softer combination than the explicit copyright / GPL combo.

Thanks again for your patience. Live and learn :-)
